vim ./tasks/Scala/InstallScalaTools/InstallScalaToolsV1/task.json
vim ./tasks/Scala/InstallScalaTools/InstallScalaToolsV1/installScalaTools.sh
vim ./tasks/Scala/InstallScalaTools/InstallScalaToolsV1/package.json
vim ./tasks/Scala/CompileInstallJar/CompileInstallJarV1/task.json
vim ./tasks/Scala/CompileInstallJar/CompileInstallJarV1/package.json
vim ./tasks/Scala/CompileInstallJar/CompileInstallJarV1/compileinstalljar.sh
vim ./tasks/Scala/WaitForClusterReboot/WaitForClusterRebootV1/task.json
vim ./tasks/Scala/WaitForClusterReboot/WaitForClusterRebootV1/package.json
vim ./tasks/Scala/InstallSpark/InstallSparkV1/task.json
vim ./tasks/Scala/InstallSpark/InstallSparkV1/package.json
vim ./tasks/Scala/UninstallCodeFromCluster/UninstallCodeFromClusterV1/task.json
vim ./tasks/Scala/UninstallCodeFromCluster/UninstallCodeFromClusterV1/package.json
vim ./tasks/Scala/StartCluster/StartClusterV1/task.json
vim ./tasks/Scala/StartCluster/StartClusterV1/package.json
vim ./tasks/Scala/RunSbtTests/RunSbtTestsV1/task.json
vim ./tasks/Scala/RunSbtTests/RunSbtTestsV1/runsbttests.ts
vim ./tasks/Scala/RunSbtTests/RunSbtTestsV1/package.json
vim ./tasks/Scala/RunSbtTests/RunSbtTestsV1/runsbttests.sh
vim ./tasks/Scala/RunSbtTests/RunSbtTestsV1/runsbttests.js
